version: "3.7"
services:
  application:
    container_name: measure-shelter-app
    build: .
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - mongodb
  mongodb:
    container_name: meausre-shelter-mongo
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
      